# Configure workspace directories

- name: Create workspace directory
  file:
    path: "{{general.local_home}}/work"
    state: directory

- name: Setup GOPATH
  file:
    path: "{{general.local_home}}/work/go"
    state: directory

- name: Setup vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{general.local_home}}/.local/share/nvim/site/autoload/plug.vim"
